// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHuwlZXLgX-HeeS7z1jfnSDALsoZxjGE',
    appId: '1:866058182933:web:05e54ae57d7a04ba34891c',
    messagingSenderId: '866058182933',
    projectId: 'labaneta-sweet-418b8',
    authDomain: 'labaneta-sweet-418b8.firebaseapp.com',
    storageBucket: 'labaneta-sweet-418b8.appspot.com',
    measurementId: 'G-20FTCMYV57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qHo5Qtwx6jH4VrNOzYwlXM7yb4XpvXo',
    appId: '1:866058182933:android:70c1eade32ac9bc734891c',
    messagingSenderId: '866058182933',
    projectId: 'labaneta-sweet-418b8',
    storageBucket: 'labaneta-sweet-418b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6etobThL57BW0NfihvI7jDUXAWmlTdJI',
    appId: '1:866058182933:ios:638f974a87eb068534891c',
    messagingSenderId: '866058182933',
    projectId: 'labaneta-sweet-418b8',
    storageBucket: 'labaneta-sweet-418b8.appspot.com',
    iosBundleId: 'com.labaneta.labanetaSweet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6etobThL57BW0NfihvI7jDUXAWmlTdJI',
    appId: '1:866058182933:ios:638f974a87eb068534891c',
    messagingSenderId: '866058182933',
    projectId: 'labaneta-sweet-418b8',
    storageBucket: 'labaneta-sweet-418b8.appspot.com',
    iosBundleId: 'com.labaneta.labanetaSweet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGHuwlZXLgX-HeeS7z1jfnSDALsoZxjGE',
    appId: '1:866058182933:web:73a4424ad6d43f4434891c',
    messagingSenderId: '866058182933',
    projectId: 'labaneta-sweet-418b8',
    authDomain: 'labaneta-sweet-418b8.firebaseapp.com',
    storageBucket: 'labaneta-sweet-418b8.appspot.com',
    measurementId: 'G-49Y2G1HTSC',
  );
}
